# Generated by Django 4.2.4 on 2026-02-19 03:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=120)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('customer_notes', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('dashboard', 'Dashboard')], default='whatsapp', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BotFlowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('message_text', models.TextField(blank=True, default='')),
                ('interaction_type', models.CharField(choices=[('text_only', 'Solo texto'), ('option_list', 'Menu interactivo'), ('url_button', 'Boton con enlace')], default='text_only', max_length=20)),
                ('menu_title', models.CharField(blank=True, default='', max_length=120)),
                ('menu_description', models.TextField(blank=True, default='')),
                ('menu_button_text', models.CharField(blank=True, default='Ver opciones', max_length=30)),
                ('link_button_text', models.CharField(blank=True, default='', max_length=40)),
                ('link_button_url', models.URLField(blank=True, default='')),
                ('is_start', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_default_nodes', to='app.botflownode')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='app.botflow')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('payload_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('quote_url', models.URLField(blank=True, default='')),
                ('availability_type', models.CharField(choices=[('permanent', 'Permanente'), ('temporary', 'Temporal')], default='permanent', max_length=20)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_until', models.DateField(blank=True, null=True)),
                ('default_duration_minutes', models.PositiveIntegerField(default=60)),
                ('slot_step_minutes', models.PositiveIntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('conversation_state', models.CharField(choices=[('idle', 'Sin estado'), ('quote', 'Cotizacion'), ('booking', 'Agendado')], default='idle', max_length=20)),
                ('booking_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='app.botflow')),
                ('active_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.botflownode')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceWeeklyRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')])),
                ('label', models.CharField(blank=True, default='', max_length=80)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_ranges', to='app.service')),
            ],
            options={
                'ordering': ['weekday', 'order_index', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ServicePreSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_required', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_until', models.DateField(blank=True, null=True)),
                ('max_bookings', models.PositiveIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_sales', to='app.service')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exception_type', models.CharField(choices=[('closed', 'Bloquear fecha'), ('special_range', 'Horario especial'), ('max_bookings', 'Limite de eventos por fecha')], max_length=20)),
                ('range_mode', models.CharField(choices=[('replace', 'Reemplazar horarios del dia'), ('add', 'Agregar horario adicional')], default='replace', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('max_bookings', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='app.service')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('direction', models.CharField(choices=[('incoming', 'Entrante'), ('outgoing', 'Saliente')], max_length=20)),
                ('message_type', models.CharField(default='text', max_length=30)),
                ('payload_id', models.CharField(blank=True, default='', max_length=120)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotFlowOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('trigger_key', models.CharField(max_length=120)),
                ('action_type', models.CharField(choices=[('go_to_message', 'Ir a otro mensaje'), ('quote_service', 'Enviar cotizacion de servicio'), ('book_service', 'Enviar enlace para agendar'), ('open_link', 'Enviar enlace'), ('go_to_start', 'Volver al inicio'), ('close', 'Cerrar conversacion')], default='go_to_message', max_length=20)),
                ('external_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_options', to='app.botflownode')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app.botflownode')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.service')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BookingIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_option_key', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intent', to='app.booking')),
                ('selected_pre_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_intents', to='app.servicepresale')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_intents', to='app.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_intents', to='app.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='pre_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='app.servicepresale'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='app.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.user'),
        ),
        migrations.AddConstraint(
            model_name='botflowoption',
            constraint=models.UniqueConstraint(fields=('node', 'trigger_key'), name='uniq_node_option_trigger'),
        ),
        migrations.AddConstraint(
            model_name='botflownode',
            constraint=models.UniqueConstraint(fields=('flow', 'key'), name='uniq_flow_node_key'),
        ),
    ]
