# Generated by Django 4.2.4 on 2026-02-19 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_required', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_until', models.DateField(blank=True, null=True)),
                ('max_bookings', models.PositiveIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pre_sale',
        ),
        migrations.RemoveField(
            model_name='bookingintent',
            name='selected_pre_sale',
        ),
        migrations.RemoveField(
            model_name='service',
            name='payload_key',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slot_step_minutes',
        ),
        migrations.AddField(
            model_name='service',
            name='booking_interval_minutes',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='service',
            name='internal_code',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('dashboard', 'Panel')], default='whatsapp', max_length=20),
        ),
        migrations.DeleteModel(
            name='ServicePreSale',
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='app.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='app.servicepackage'),
        ),
        migrations.AddField(
            model_name='bookingintent',
            name='selected_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_intents', to='app.servicepackage'),
        ),
    ]
