# Generated by Django 4.2.4 on 2026-02-20 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_servicepackage_remove_booking_pre_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_role',
            field=models.CharField(choices=[('user', 'Usuario'), ('bot', 'Bot'), ('agent', 'Agente')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('doubts', 'Dudas')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('resolved', 'Resuelto')], default='pending', max_length=20)),
                ('last_user_message_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversation', to='app.user')),
            ],
            options={
                'ordering': ['status', '-updated_at'],
            },
        ),
    ]
