# Generated by Django 5.2.3 on 2025-10-07 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_booking_service_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_command',
        ),
    ]
