# Generated by Django 5.2.3 on 2026-01-05 02:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_last_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id_days', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id_feriado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='service',
            old_name='valid_date',
            new_name='available_from',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='anticipated_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='valid_days',
        ),
        migrations.RemoveField(
            model_name='service',
            name='valid_hours_end',
        ),
        migrations.RemoveField(
            model_name='service',
            name='valid_hours_start',
        ),
        migrations.AddField(
            model_name='service',
            name='available_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='days',
            field=models.ManyToManyField(related_name='services', to='app.day'),
        ),
        migrations.CreateModel(
            name='ServiceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='app.service')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='service_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.servicetier'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id_block_time', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(max_length=50)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='app.day')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='app.service')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentAvailable',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('disponible', 'Disponible')], default='disponible', max_length=20)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app.servicetier')),
                ('block_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app.timeblock')),
            ],
        ),
    ]
