# Generated by Django 4.2.4 on 2026-02-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_message_sender_role_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='booking_interval_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
