# Generated by Django 5.2.3 on 2026-02-11

import uuid

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_day_feriado_rename_valid_date_service_available_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="source",
            field=models.CharField(
                choices=[("whatsapp", "WhatsApp"), ("dashboard", "Dashboard")],
                default="whatsapp",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="direction",
            field=models.CharField(
                choices=[("incoming", "Entrante"), ("outgoing", "Saliente")],
                default="incoming",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(default="text", max_length=30),
        ),
        migrations.AddField(
            model_name="message",
            name="payload_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="raw_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="service",
            name="payload_id",
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="servicetier",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="booking_token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="user",
            name="conversation_state",
            field=models.CharField(
                choices=[("idle", "Sin estado"), ("cotizar", "Cotizando"), ("agendar", "Agendando")],
                default="idle",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name="BookingIntent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("source_payload_id", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Abierto"), ("completed", "Completado"), ("cancelled", "Cancelado")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intent",
                        to="app.booking",
                    ),
                ),
                (
                    "selected_tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_intents",
                        to="app.servicetier",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_intents",
                        to="app.service",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_intents",
                        to="app.user",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
