# Generated by Django 4.2.4 on 2026-02-11 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_refactor_booking_flow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-time', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='botresponse',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='servicetier',
            options={'ordering': ['service__name', 'price']},
        ),
        migrations.AlterModelOptions(
            name='timeblock',
            options={'ordering': ['service__name', 'day__id_days', 'start_time']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='app.servicetier'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.user'),
        ),
        migrations.AlterField(
            model_name='botresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_responses', to='app.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.user'),
        ),
    ]
