# Generated by Django 4.2.4 on 2026-02-11

import uuid

from django.db import migrations, models


def backfill_unique_tokens(apps, schema_editor):
    User = apps.get_model("app", "User")
    used_tokens = set()

    for user in User.objects.all().order_by("id"):
        token = user.booking_token
        if token is None or token in used_tokens:
            new_token = uuid.uuid4()
            while new_token in used_tokens:
                new_token = uuid.uuid4()
            user.booking_token = new_token
            user.save(update_fields=["booking_token"])
            used_tokens.add(new_token)
            continue
        used_tokens.add(token)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_booking_options_alter_botresponse_options_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_unique_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="booking_token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
